services:
  ana-site:
    container_name: ana_site
    image: beagalmeida/ana-capis:v0.0.2
    platform: linux/amd64
    restart: always
    ports: 
    - 3000:3000
    labels:
    - traefik.http.routers.my-container.rule=Host(`anacapistrano.vet`)